cont quiz=[
{
	q:'1.Who is known as father of Java Programming Language?',
	options:['James Gosling','M. P Java','Charel Babbage','Blais Pascal'],
	answer:0
},
{
	q:'Which provides runtime environment for java byte code to be executed?',
	options:['JDK','JVM','JRE','JAVAC'],
	answer:1
},
{
	q:'3.What is byte code in Java?',
	options:['Code generated by a Java compiler','Code generated by a Java Virtual Machine','Name of Java source code file','Block of code written inside a class'],
	answer:0
},
{
	q:'4.Which of the following are not Java keywords ?',
	options:['double','switch','then','instanceof'],
	answer:2
},
{
	q:'5.Which of these have highest precedence?',
	options:['()','++','-','>>'],
	answer:0
},
{
	q:'6.Which variables are created when an object is created with the use of the keyword 'new' and destroyed when the object is destroyed?',
	options:['Local variables','Static variables','Instance variables','Class Variables'],
	answer:2
},
{
	q:'7.What is garbage collection in the context of Java?',
	options:['Java deletes all unused java files on the system.','Memory used by the object with no reference is automatically reclaimed.','The JVM cleans output of Java program with error.','Any unused package in a program automatically gets deleted.'],
	answer:1
},
{
	q:'8.Which one is a template for creating different objects ?',
	options:['An Array','A class','Interface','Method'],
	answer:1
},
{
	q:'9.Which one is true about a constructor ?',
	options:['A constructor must have the same name as the class it is declared within.','A constructor is used to create objects.','A constructor may be declared private','All of the above'],
	answer:3
},
{
	q:'10.Which of these operators is used to allocate memory to array variable in Java?',
	options:['Alloc','Malloc','New malloc','New'],
	answer:3
},


]